### ISSUE TITLE
Don't close modal after each add/delete tag operation

### ISSUE THREAD

**Issue by melvin4u445** [ARK-Builders/ARK-Navigator#100]
The below modal is dismissed each time a tag is added or deleted. The UX could be improved by keeping the modal open till the user manually closes the modal. Instead, tapping outside the modal could dismiss it and maybe a close button could also be added to dismiss it?

![image](https://user-images.githubusercontent.com/17034768/136668205-01899f58-c302-4c1a-be14-eda4f12f4a74.png)

**Comment by kirillt** [comment]
Reworked in #117
