### ISSUE TITLE
Glitch when viewing image in full screen

### ISSUE THREAD

**Issue by melvin4u445** [ARK-Builders/ARK-Navigator#104]
When viewing an image in full screen, there is a white border at the bottom of the screen for a few milliseconds. Would be good if we can hide it. 

https://user-images.githubusercontent.com/17034768/136684947-a934b0d1-7614-4edd-a134-028c3953290b.mp4

**Comment by kirillt** [comment]
@vedranqa this issue should be solved in #119.
Could you try it and compare builds _129_ and _154_?

**Comment by vedranqa** [comment]
@kirillt checked both versions, on both versions issue is active
build129
https://user-images.githubusercontent.com/60543054/142240546-f7867cd6-cb60-482f-8a4b-c04db1995e5e.mp4

build154

https://user-images.githubusercontent.com/60543054/142240662-1b39225a-9835-4b93-b2dc-c0eb7f28229d.mp4

**Comment by kirillt** [comment]
@mdrlzy seems to be still present in #119.
_Build 129_ is this: https://github.com/ARK-Builders/ARK-Navigator/actions/runs/1415685061

On the very first video the white border appears when _entering_ fullscreen.
On these last videos the white border appears when _leaving_ fullscreen.

This issue isn't urgent for now, but better to fix later.

**Comment by kirillt** [comment]
Similar problems appeared after we've implemented screen rotation:

https://user-images.githubusercontent.com/581023/145683403-f5b66c2d-9b54-4306-9005-96fbc51c4000.mp4

https://user-images.githubusercontent.com/581023/145683390-a518e9cd-1c59-4a65-a0f5-e35e05408e8e.mp4
