### ISSUE TITLE
Tags are not displayed when added from another root folder

### ISSUE THREAD

**Issue by melvin4u445** [ARK-Builders/ARK-Navigator#111]
I have added the following folders as separate root folders:
- DCIM
- DCIM/Screenshots

I opened Manage Folders>Compass button on DCIM/Screeshots, opened an image and added a tag to it. 
Then I opened Manage Folders>Compass button on DCIM and checked if the newly added tag is listed. Turns out it's not listed. 

It would make sense that the newly added tag is displayed when opening DCIM root since DCIM/Screenshots is a subfolder of that folder

**Comment by melvin4u445** [comment]
Yeah, I added DCIM/Screenshots before adding DCIM

> "Root" is a folder where we store the tags database (.ark-tags file)

What happens if a file is moved to another folder? Will it lose all its tags?

**Comment by melvin4u445** [comment]
Raised #112 to address the nested folder issue

**Comment by kirillt** [comment]
@melvin4u445
> What happens if a file is moved to another folder? Will it lose all its tags?

Right, all tags will be lost.

Closing this issue since it actually wasn't intended to work this way, but downgrading a root into a favorite would be cool feature.
