### ISSUE TITLE
Support plain text files

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#116]
The app should support previewing plain text files (`.txt`) and editing them in an external app.

**Comment by kirillt** [comment]
Open question: how should we determine if a resource is "plain text"? Ideally, we would like to treat not only files with `.txt` extension. Is it a good idea to take first _N_ bytes, attempt conversion of them to UTF-8 and, in case of success, treat the file as plain text?

**Comment by mdrlzy** [comment]
I think we can use [Apache Tika](https://tika.apache.org/)
`val fileType = Tika().detect(inputStream)`
