### ISSUE TITLE
Use resources metadata in sorting procedures

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#125]
We should avoid querying filesystem during resources sorting (by name, size or modification time).
All this data should be stored in index as metadata. Size and modification time is already stored.

**Comment by vedranqa** [comment]
@kirillt need more info/hint here. thanks

**Comment by kirillt** [comment]
@vedranqa that's about time measurement. Using a huge folder, measure please how much seconds it takes to sort **by size** and **by last modified** (other sortings should be quick already)

**Comment by vedranqa** [comment]
here si the log of measurment, this sort is fast enought. 1276files, 290mb folder siz
[logSizeLastMod.txt](https://github.com/ARK-Builders/ARK-Navigator/files/7610307/logSizeLastMod.txt)
e

**Comment by kirillt** [comment]
@vedranqa we need more files in the folder to measure this, like 5000, so sorting without optimization would take 5 sec or more.
Also, right now there is no measurement for this in the log (we will add it). If you can measure manually how long "progress circle" with label "sorting" spins, it would be great.

**Comment by kirillt** [comment]
@vedranqa Dinar has added time measurement for sorting, now we can make initial measurement by looking into the logs (build _171_).

**Comment by vedranqa** [comment]
Build 171:
space.taran.arknavigator D/resources-index: **4408** resources returned
space.taran.arknavigator D/resources-screen: sorting by **SIZE** of 1460 resources took **672 milliseconds**
space.taran.arknavigator D/resources-screen: sorting by **LAST_MODIFIED** of 1460 resources took **689 milliseconds**

Bulid 172:
space.taran.arknavigator D/resources-screen: sorting by **LAST_MODIFIED** of 4407 resources took **53 milliseconds**
space.taran.arknavigator D/resources-screen: sorting by **SIZE** of 4407 resources took **21 milliseconds**

Tested on Xiaomi a2, Android 9

**Comment by kirillt** [comment]
@vedranqa awesome (I'm assuming in the test with _build 172_ we have the same 4408 resources).
So we have **x32** performance boost in case of sorting by size and **x13** boost in case of sorting by _last modified_.
Not sure if there really any difference between those two attributes in terms of query speed, but certainly we solved the problem.
