### ISSUE TITLE
Thumbnails and previews missing

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#138]
![_1](https://user-images.githubusercontent.com/581023/142668081-a23ac16a-1c05-43e4-a0f2-f59a5af79efe.jpg)
![_2](https://user-images.githubusercontent.com/581023/142668093-b666c3c8-017b-43ec-9507-e86955a8bc05.jpg)
![_3](https://user-images.githubusercontent.com/581023/142668099-488b529e-7c2c-4a00-8048-52295ee5cfe7.jpg)

**Comment by kirillt** [comment]
Probably this happens for existing resources after the app restarted. New resources have their previews and thumbnails loaded.

This issue reproduces on my Android 9 device and it doesn't on Android 11.

**Comment by kirillt** [comment]
The way to reproduce (I guess, on any device, but better to check):
1. Index a folder, previews and thumbnails must be visible.
2. Close the app.
3. Go to Android settings, find Apps section, locate the app.
4. Go to Storage section of the app, press "clear cache".
5. Run the app again, open the same folder.
Expected: previews and thumbnails are still visible.
Actual: previews and thumbnails are missing.

Explanation: apparently, we store the index as app's _data_ and previews/thumbnails as app's _cache_.
The index still contains all resources, so re-indexing doesn't heppen, but previews generation is triggered only during indexing.

**Comment by vedranqa** [comment]
Creating folder: 
space.taran.arknavigator D/previews: previews provided in **12553ms**
space.taran.arknavigator D/resources-index: 1572 resources returned

After cleaning cache:
/space.taran.arknavigator D/previews: previews provided in **25169ms**
sace.taran.arknavigator D/resources-index: 1572 resources returned


Phone: Xiaomi A2
Android: 10
Folder: 1572 files, ~400mb size

Used build 165

**Comment by kirillt** [comment]
@vedranqa that's strange.. no mistakes? Was the second result (after cleaning cache) _opening_ or _creating_ the folder?

**Comment by vedranqa** [comment]
@kirillt this second case _After cleaning cache_ is **Opening** same folder like in first case.

**Comment by kirillt** [comment]
Implemented in #143

**Comment by vedranqa** [comment]
This is active on main build (id 204) after deleting cache we dont have thumbnails and previews.

**Comment by vedranqa** [comment]
Build 204 issue is active.

Build 208 seems ok 


We can resolve this task. 
Video is large, open [Link](https://drive.google.com/file/d/1o6SCMf8-2_a_kFKz5ngmwSe07xF5MYy_/view?usp=sharing)

**Comment by kirillt** [comment]
@vedranqa build 204 is too early, build 208 is correct one.
Thank you, it looks good.
