### ISSUE TITLE
Resource modification is not detected

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#152]
https://user-images.githubusercontent.com/581023/145065132-2e5e8a69-5ddd-4d6f-b1b0-be432da95278.mp4

How to reproduce (example with images):
* open a folder with some images, let it index
* switch to image editor (I use "Simple Gallery" with embedded editor)
* modify the content of the image
* switch back to ARK Navigator
* (it crashes) restart the app
* open the folder again

Expected behaviour:
* old version is removed from resources grid
* new version is displayed

Actual behaviour:
* old version is present
* new version is missing

**Apparently, re-indexing doesn't trigger although it should be triggered because path of the image has updated _last modified_.**
**So, the id isn't re-calculated and both preview and thumbnail aren't re-generated.**

**Comment by vedranqa** [comment]
Checked on Andorid 10, same behavior. Build no: 181

**Comment by kirillt** [comment]
Dinar has discovered that the issue originates from Glide's cache.
> Active resources - Is this image displayed in another View right now?
Memory cache - Was this image recently loaded and still in memory?
Resource - Has this image been decoded, transformed, and written to the disk cache before?
Data - Was the data this image was obtained from written to the disk cache before?

> In fact, the cache keys for steps 1-3 (Active resources, memory cache, resource disk cache) also include a number of other pieces of data including:
The width and height
The optional Transformation
Any added Options
The requested data type (Bitmap, GIF, etc)

**Comment by mdrlzy** [comment]
Possible solution is to add custom image signature for glide cache validation.
https://bumptech.github.io/glide/doc/caching.html#custom-cache-invalidation

**Comment by kirillt** [comment]
@mdrlzy this looks good, I think `ResourceId` should be enough as signature.
It's interesting though, why the caches are not invalidated when image size is changed.

**Comment by kirillt** [comment]
Closed by #201
