### ISSUE TITLE
Crash app from Navigate Data

### ISSUE THREAD

**Issue by cnzqa** [ARK-Builders/ARK-Navigator#158]
On the video you will see easy way to crash the app. 

Steps to reproduce:
1. open app and go to navigate data
2. When indexing is loading click on Tags on
3. App will get crashed 

Log: 
[crashFromNavigate.txt](https://github.com/ARK-Builders/ARK-Navigator/files/7706004/crashFromNavigate.txt)

Video:

https://user-images.githubusercontent.com/60543054/145867324-0d7c1318-50f4-4f91-859c-1f4a2482498f.mp4

seems like related to #150

**Comment by kirillt** [comment]
`[Tags on/off]` (or "cloud" button) was replaced by modes switching button. `[Focus mode]` on empty query must be equal to `[tags off]`. See #22 and #238.
