### ISSUE TITLE
Glitch with preview and thumbnails

### ISSUE THREAD

**Issue by vedranqa** [ARK-Builders/ARK-Navigator#164]
Opening files there is flash of preview icon before opening photo and the sam e on thumbnails. 
Details in video

https://user-images.githubusercontent.com/60543054/146911371-8f36dc55-96c2-4698-b0de-40a80fb6f5e8.mp4

Android 10
Xiaomi A2
Build 208

**Comment by kirillt** [comment]
Fixed in #172
