### ISSUE TITLE
Zip file have blank icon

### ISSUE THREAD

**Issue by cnzqa** [ARK-Builders/ARK-Navigator#193]
Zip file have blank icon like we have on .jpg, .mp3, etc, should be nice to have it like on other extension. 
![image](https://user-images.githubusercontent.com/60543054/151226332-c87835b9-8a56-4496-a2e2-ef8435783844.png)

Verison 252
Emulator Pixel 6

**Comment by kirillt** [comment]
@vedranqa interesting idea. Yes, we should depict something specific to archive in this case.
Maybe we even should introduce category of archives (in the same row as image, video, document, etc.).
