### ISSUE TITLE
Fragments must be restorable

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#29]
Right now, if a user leaves the app on, e.g. `GalleryFragment`, and switches to another app, and OS kills our app — after Android attempts to restore our app, it will crash. The reason is that Android can restore only fragments with empty constructors.

Fragments should be reworked to gain this capability, particularly `GalleryFragment` and `ResourcesFragment`.

**Comment by kirillt** [comment]
Related #4

**Comment by melvin4u445** [comment]
Not sure how to reproduce this. I tried this:
- opened a picture in the app
- minimised the app and opened a few different apps
- returned to the app after a few minutes

The OS didn't reallocate the resources assigned to the app and it opened instantly without a hitch, so not sure how to reproduce this.

**Comment by melvin4u445** [comment]
Okay, that was my assumption too. Thanks for confirming! I will try this again

**Comment by vedranqa** [comment]
Checked with steps form PR #135  and fine. Used buld 170 and device was Xiaomi A2
[logL.txt](https://github.com/ARK-Builders/ARK-Navigator/files/7645222/logL.txt)

**Comment by kirillt** [comment]
Closed by #135
