### ISSUE TITLE
Improve bulk operations

### ISSUE THREAD

**Issue by mdrlzy** [ARK-Builders/ARK-Navigator#292]
- Tags migration on move/copy
- Delete confirmation dialog
- Create a new file on move/copy if such name already exists
- Sharing
- Common tags editing dialog

**Comment by kirillt** [comment]
> * Tags migration on move/copy

This one requires #40, which we should implement using [arklib](https://github.com/ARK-Builders/arklib).

> * Delete confirmation dialog

Yes, and other destructive operations like moving.

> * Create a new file on move/copy if such name already exists

Because filenames don't matter and we will have our own resource names: #254
