### ISSUE TITLE
WebP image type support

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#306]
The app needs to support viewing images like WebP and maybe some other types.

Example of such an image (inside an archive):
[mesari.zip](https://github.com/ARK-Builders/ARK-Navigator/files/9423473/mesari.zip)

**Comment by mdrlzy** [comment]
[Fresco](https://github.com/facebook/fresco) seems to support more image formats than Glide. Also it supports Webp natively when glide relies on Android framework.
