### ISSUE TITLE
Bounty #2 for Shubert

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#320]
We need to solve 2 issues in Navigator:

- #90
We need controls to hide/forget root/favorite folders. This feature should have an option to also delete the folder with all files in it. Such a destructive option must require confirmation from user.

- [Provide implementation for ResourceIndex interface in arklib-android repo](https://github.com/ARK-Builders/arklib-android/pull/27/files#diff-cbdf4d93658fb15c65c63)
  - [x] The easiest way to do it is to just copy `PlainResourcesIndex` and `AggregatedResourcesIndex` classes into `arklib-android`. This would also require to copy some code working with RoomDB. The copied code must be eliminated from Navigator and be replaced with calls to `arklib-android`.
  - [x] A harder but better way would be to create binding to newer `ResourceIndex` implementation from `arklib` (our Rust library). This would eliminate RoomDB completely from our project and would implement #142 in Navigator and all apps using `arklib-android`.
  
Separate pull-requests should be used for these issues.

**Comment by kirillt** [comment]
The bounty: https://gitcoin.co/issue/29649

**Comment by Sixto5** [comment]
Hey @kirillt,

Thank you for sharing this project!

I'm reaching out to share our invitation to support your issue via OpenQ marketplace. We are permissionless and free, see more here: https://www.openq.dev/

Zero hassle from your side 🙂 We will mirror your bounty, adding the same budget.
Devs from our community might solve your issue. So then we can support you meanwhile our marketplace grows.

If you give me your thumbs up we will do it and share the link again here to you for full transparency!

**Comment by kirillt** [comment]
https://github.com/ARK-Builders/arklib-android/pull/29
https://github.com/ARK-Builders/arklib-android/pull/32
https://github.com/ARK-Builders/arklib-android/pull/33
