### ISSUE TITLE
Persisted sorting preferences

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#35]
Sorting preferences must be saved between runs. E.g. if a user chooses "sort by size, descending", this choice must be still enabled even after the user left the app, or the app crashed and restarted.

**Comment by CloudLevi** [comment]
Sorting preferences are now persistent.
Also, fixed an a bug where the app would crash when "Extension" sorting is selected (The app wasn't checking whether the current file name has an extension or not).

**Comment by kirillt** [comment]
Implemented in #62
