### ISSUE TITLE
Remember tags on/off state

### ISSUE THREAD

**Issue by melvin4u445** [ARK-Builders/ARK-Navigator#59]
The tag on/off state is not remembered when returning back after viewing media

As you see in the video, tags were turned ON before viewing media. When returning back to the view, the button shows as OFF again

https://user-images.githubusercontent.com/17034768/132107055-29f0ca9e-c3d6-429b-8e59-448f8357d93a.mp4

**Comment by kirillt** [comment]
Should be fixed now (#37)

**Comment by melvin4u445** [comment]
Looks okay now 👌
