### ISSUE TITLE
Huge images loading

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#63]
When we load preview for an image, we should create hint for a user about size of it. Spinner animation also would not hurt. We should also verify later that even 100mb images load successfully.

**Comment by vedranqa** [comment]
For huge folders we have spinner with _Indexing_  and _Sorting_
Checked on build 167 @kirillt

**Comment by kirillt** [comment]
@vedranqa that's different actually, this issue is about loading huge **images** in gallery view.
Something like high-resolution photo, you can take this one for testing:
https://www.taran.space/photo/20201005_Thessaloniki_4.png

Curious if it will load and in what time.

**Comment by vedranqa** [comment]
@kirillt This photo is about 70mb, after I open image its not show and apps get crashed. Buidl 167
[logwBigPhoto.txt](https://github.com/ARK-Builders/ARK-Navigator/files/7610258/logwBigPhoto.txt)

**Comment by kirillt** [comment]
@vedranqa intersting result.. what Android version?

For me, it doesn't load on Android 9, but without crashing.

**Comment by vedranqa** [comment]
This is reporudced on Xiaomi A2 Andorid 9 @kirillt

**Comment by kirillt** [comment]
@vedranqa gotcha, Dinar observed this too, let's discuss the crash in this ticket: https://github.com/ARK-Builders/ARK-Navigator/issues/139
This one is about performance and indication for a user when loading is too slow.

**Comment by mdrlzy** [comment]
Implemented in #192
