### ISSUE TITLE
Crashes reporting

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#78]
Crashes should be reported automatically, this will save time for extracting logs.
This setting must be configurable in settings menu (#77) and be enabled by default for debug builds and disabled for production.

**Comment by kirillt** [comment]
This library should be good https://github.com/ACRA/acra

**Comment by kirillt** [comment]
_Release_ build must spawn email app with pasted crash log and our e-mail as the recipient.
 _Debug_ build must contain tiny email sender dependency and send report automatically.

**Comment by salihyalcin** [comment]
Hi, can I ask one question regarding crash reporting? As far as I understand from the requirements, are you good with using Firebase Crashlytics? The more app has users, the more emails need to be sent. I think solving this problem in a clever way would be with a service that provides crash reporting. I don't know maybe you have some concerns regarding privacy but I recommend firebase for this issue.

**Comment by kirillt** [comment]
@salihyalcin We have considered Firebase Crashlytics for this, but yes, here is the privacy concern. The app's purpose is to work with local files mostly (although remote resources might be added later). Hence it's possible to have zero internet connections for the app's work and this is security bonus.

I think also that to send e-mail is the easiest sane way to solve the problem. Also the app will be checked later to be able to work without Google Services and I guess they are necessary for Crashlytics.

**Comment by kirillt** [comment]
Also a button "send current log" would be useful for debugging purposes. Sometimes it's really annoying to connect cable.
