### ISSUE TITLE
Images in folder picker don't draw sometimes

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#81]
Steps to reproduce:
1. On folders screen, press "+" button.
2. Go to a folder with pictures. They draw without problems.
3. Go to a nested folder with pictures.
4. Go back.
5. Pictures which were visible before, became gray squares.

https://user-images.githubusercontent.com/581023/134819865-d4c47341-a904-4f62-8719-8cda387169b6.mp4

**Comment by melvin4u445** [comment]
Tested this on the latest `main` branch. 
Not sure if this is the same issue but I can reproduce this even without the steps above. 

Steps:
1. On a freshly installed app, press the plus button
2. Open a nested folder (DCIM/Screenshots in my example)
As seen in the below video, some of the images are gray and some are not. 
As expected, when I add the folder as root and view its contents, I can see all the images. 

https://user-images.githubusercontent.com/17034768/135710123-c3701acc-bec1-4686-88b3-d314b6199bf2.mp4

**Comment by kirillt** [comment]
We don't draw thumbnails in folder picker anymore — only generic icons.
