### ISSUE TITLE
Remove "Emulated" and show root folders right away

### ISSUE THREAD

**Issue by melvin4u445** [ARK-Builders/ARK-Navigator#88]
Is there a reason to show the root folders under "Emulated" or can we just show them in the main view without one additional hierarchy? 

![image](https://user-images.githubusercontent.com/17034768/135763418-1771bf79-c646-4298-976c-44aaa14e6fc5.png)

**Comment by kirillt** [comment]
Yes, there is. The highest level of hierarchy here is _device_ and `emulated` is internal memory, while something like `9C33-6BBD` (in my case) is external memory (SD card). Virtual devices should be also implemented eventually (see https://github.com/ARK-Builders/ARK-Navigator/issues/24).

Devices also are starting points in the folder picker (`+` button).

**Comment by melvin4u445** [comment]
Agreed!
