### ISSUE TITLE
Add an option to delete root folders

### ISSUE THREAD

**Issue by melvin4u445** [ARK-Builders/ARK-Navigator#90]
There is no way to delete a root folder now. Would be good to add this option at some point
Deleting Favorited folders could also be dealt with at the same time

**Comment by kirillt** [comment]
Right, both _roots_ and _favorites_ must be removable.

**Comment by kirillt** [comment]
We need that feature: https://github.com/ARK-Builders/ARK-Navigator/issues/221

But it slightly conflicts with this one. Maybe we need to implement 2 operations instead:
* `[hide]` for roots — but after re-installation we would get all roots in the filesystem again
* `[forget]` for favorites

@melvin4u445 what do you think?

**Comment by melvin4u445** [comment]
I guess that would work. When I raised this ticket, my idea was that it should be hide-able/delete-able from the UI if the user wants to do that so. If we are hiding instead of deleting the root folders, maybe we could also have an option to show them again?

**Comment by darkovski88** [comment]
@kirillt since im working on this ticket, can you please give me more info on what should implemented here more precisely?
From the comments above I think we need to extent the capability of the `roots` to have the possibility to be hidden and removed. How should this work, how can once hidden roots be visible again?

**Comment by kirillt** [comment]
This UI seems sensible to me:
* add `[trash bin]` icon in folder-actions section (near tiny `[+]` and `[compass]` buttons)
* add `[hidden folders]` label, which is gray-colored text label with text like "3 root folders are hidden"
    * make the label clickable, when it is clicked, display list of hidden roots
    * each line in the dialog should contain `[un-hide]` checkbox
    * if `[un-hide]` is clicked, make the corresponding root visible again (but don't leave the dialog, allowing the user to un-hide more roots)
    * if `[un-hide]` is clicked again, cancel un-hiding
    * the dialog should have `[close]` button which commits changes

**Comment by melvin4u445** [comment]
Checkboxes are not very mobile-friendly. Instead of checkboxes, could we do it 
- so that the hidden root tiles are gray and clickable
- tapping a hidden root turns it into a green tile (or some other colour)
- tapping again turns it into a gray tile again
- user can select multiple roots and close the dialog to apply the changes

Two more things to think about. 
- Instead of a dialog, can it be a separate view since dialogs are not very mobile-friendly either
- We probably need two buttons, one to close the dialog/view without saving the changes, and another one to apply the changes. 
  - If it is a dialog, we could show an X button to close without saving. 
  - If it is a view, we could use a "Back" button or "<" button going back without making changes.
  -  and in both cases an "Apply" button to apply changes.

**Comment by kirillt** [comment]
@melvin4u445 good points, agree with everything.

**Comment by kirillt** [comment]
Implemented in #90
