### ISSUE TITLE
[Clear selection] button for tag selector

### ISSUE THREAD

**Issue by melvin4u445** [ARK-Builders/ARK-Navigator#91]
Not sure if I misunderstood the logic of the close button but I was expecting that the close button would appear next to the selected tag

![image](https://user-images.githubusercontent.com/17034768/135765696-78552154-f30b-4dc6-be2b-e458f948879a.png)

**Comment by kirillt** [comment]
Actually, it is put in this place because otherwise UI would be too "jumpy": when a user changes selection, the chips would don't stay in their places but must give some space for `x` button. It should be placed in some permanent dedicated place.

**Comment by melvin4u445** [comment]
Yeah, it would make sense to show it in a permanent place to avoid confusion :)

**Comment by kirillt** [comment]
Must be replaced with new `[clear selection]` in permanent place inside of the selector.

**Comment by kirillt** [comment]
Implemented, thanks @mdrlzy
