### ISSUE TITLE
Opening a resource in external app after a deletion of neighbour in Gallery mode

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#94]
I've experienced this once and couldn't reproduce it:
* I was listing resources in Gallery mode
* deleted one of them
* switched to another one and wanted to edit it
* pressed the `open/edit` button (for images it is with pencil on it)
* the editor opened, but had different image loaded

My guess is that it is something with indices in current selection, but I am not sure under which circumstances.

**Comment by kirillt** [comment]
Some editors might not be able to handle `EDIT` intent, this one can open any image on my phone:
https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery

**Comment by vedranqa** [comment]
Can't reproduce with this steps to reproduce, on Android 10 and Android 11, with builds: #138 and #154. on both devices I have installed Simple Gallery: Photo Manager

**Comment by kirillt** [comment]
@vedranqa thank you, could you also check with this build?
https://github.com/ARK-Builders/ARK-Navigator/actions/runs/1297849768

This was one of latest build before I found the issue.

**Comment by vedranqa** [comment]
@kirillt I've reprodce this issue on build 88.
On newer is not possible to reproduce

**Comment by kirillt** [comment]
Great, it is fixed indeed.
