### ISSUE TITLE
"Link to Web" resource kind

### ISSUE THREAD

**Issue by kirillt** [ARK-Builders/ARK-Navigator#95]
It should be possible to work with URLs using the app.
This allows a user to use our app as bookmarks keeper.

1. Sharing a link from external apps must result in saving the link into one of user's folders.
2. Links should be represented as separate entities in resources grid and gallery view.
3. Opening any link must be possible with Firefox or Chrome.
4. Opening specific links should be possible with specialized apps (e.g. YouTube, MeetUp).

Open questions:
* Storage format. The easiest way is to save every URL into HTML file.
  Batching links into one file-database per root/favorite might be more efficient, especially for indexing.

* Reading of Firefox/Chrome export files (XML).
  Should we convert those files into our format or just adapt to them?

**Comment by mdrlzy** [comment]
We also need to figure out how to generate a preview for the link.
- The file name can be replaced with the page title.
- Parsing an image. For different sites, the methods will be different (e.g. YouTube, Instagram)

**Comment by mdrlzy** [comment]
Link preview(title, description, image) can be obtained using [ogp](https://ogp.me/).

**Comment by kirillt** [comment]
Follow-up: https://github.com/ARK-Builders/ARK-Navigator/issues/235
